// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _25may24.Context;

#nullable disable

namespace _25may24.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20240527023722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_25may24.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCareer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStudent")
                        .HasColumnType("uuid");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCareer");

                    b.HasIndex("IdStudent");

                    b.ToTable("Candidate", (string)null);
                });

            modelBuilder.Entity("_25may24.Entities.Career", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Career", (string)null);
                });

            modelBuilder.Entity("_25may24.Entities.Have", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCareer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCareer");

                    b.HasIndex("IdSubject");

                    b.ToTable("Have", (string)null);
                });

            modelBuilder.Entity("_25may24.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("_25may24.Entities.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdStudent")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSubject")
                        .HasColumnType("uuid");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdSubject");

                    b.ToTable("Study", (string)null);
                });

            modelBuilder.Entity("_25may24.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("_25may24.Entities.Candidate", b =>
                {
                    b.HasOne("_25may24.Entities.Career", "Career")
                        .WithMany("Candidates")
                        .HasForeignKey("IdCareer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_25may24.Entities.Student", "Student")
                        .WithMany("Candidates")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("_25may24.Entities.Have", b =>
                {
                    b.HasOne("_25may24.Entities.Career", "Career")
                        .WithMany("Haves")
                        .HasForeignKey("IdCareer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_25may24.Entities.Subject", "Subject")
                        .WithMany("Haves")
                        .HasForeignKey("IdSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("_25may24.Entities.Study", b =>
                {
                    b.HasOne("_25may24.Entities.Student", "Student")
                        .WithMany("Studies")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_25may24.Entities.Subject", "Subject")
                        .WithMany("Studies")
                        .HasForeignKey("IdSubject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("_25may24.Entities.Career", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Haves");
                });

            modelBuilder.Entity("_25may24.Entities.Student", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("_25may24.Entities.Subject", b =>
                {
                    b.Navigation("Haves");

                    b.Navigation("Studies");
                });
#pragma warning restore 612, 618
        }
    }
}
